# persistent-volume #
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # hostPath is used for Minikube/local setups only. For cloud providers, you'd use EBS, NFS, etc.
    path: "/data/mongo"
---
# persistent-volume-claim #
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi