apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deploy
  labels: 
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express-container
        image: mongo-express
        ports:
        - containerPort: 8081
        # command: ["node", "app.js"] # Bypass default entrypoint script to start mongo-express directly and avoid connection errors
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        # - name: ME_CONFIG_BASICAUTH_ENABLED # Disable basic authentication to avoid username/password prompt on UI (for local/testing only)
        #   value: "false" # Setting this to false disables the login prompt for mongo-express UI.
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000